name: donor_darah
description: Aplikasi Donor Darah berbasis Flutter
publish_to: 'none'

version: 1.0.1+7

environment:
  sdk: ">=3.9.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # UI & Utilities
  cupertino_icons: ^1.0.8
  intl: ^0.19.0
  get: ^4.7.3
  get_storage: ^2.1.1

  # Media
  image_picker: ^1.1.2

  # Backend
  supabase_flutter: ^1.10.3

dependency_overrides:
  sign_in_with_apple: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: true
  ios: true
  windows: true
  image_path: assets/images/logo_donor.jpg
  min_sdk_android: 21

flutter:
  uses-material-design: true

  assets:
    - assets/images/
